Server.js Has Typerror  throw new TypeError('argument handler must be a function')       ^
TypeError: argument handler must be a function
    at Function.use (/home/anonymous123/DSA-Tracker/Backend/node_modules/router/index.js:392:13)
    at Function.<anonymous> (/home/anonymous123/DSA-Tracker/Backend/node_modules/express/lib/application.js:222:21)
    at Array.forEach (<anonymous>)
    at Function.use (/home/anonymous123/DSA-Tracker/Backend/node_modules/express/lib/application.js:219:7)
    at Object.<anonymous> (/home/anonymous123/DSA-Tracker/Backend/server.js:15:5)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)

Node.js v18.19.1
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
/home/anonymous123/DSA-Tracker/Backend/node_modules/router/index.js:392
      throw new TypeError('argument handler must be a function')
      ^

TypeError: argument handler must be a function
    at Function.use (/home/anonymous123/DSA-Tracker/Backend/node_modules/router/index.js:392:13)
    at Function.<anonymous> (/home/anonymous123/DSA-Tracker/Backend/node_modules/express/lib/application.js:222:21)
    at Array.forEach (<anonymous>)
    at Function.use (/home/anonymous123/DSA-Tracker/Backend/node_modules/express/lib/application.js:219:7)
    at Object.<anonymous> (/home/anonymous123/DSA-Tracker/Backend/server.js:17:5)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)

Node.js v18.19.1
[nodemon] app crashed - waiting for file changes before starting...